# Select no desktop, remove firefox.
# After setup:
# systemctl enable sshd
# ufw disable
# reboot
- name: Setup hosts after install
  hosts:
    - cachyos_server
  become: true
  vars:
    username: valankar
    dev_username: valankar-dev
    tmux_powerline: /usr/share/powerline/bindings/tmux/powerline.conf
  tasks:
    - name: Update package cache
      community.general.pacman:
        update_cache: true
    - name: Upgrade packages
      community.general.pacman:
        upgrade: true
      notify: Reboot
    - name: Install packages
      community.general.pacman:
        name:
          - cachy-update
          - compsize
          - distrobox
          - docker
          - docker-buildx
          - docker-compose
          - dua-cli
          - go-task
          - lazygit
          - neovim
          - npm
          - powerline
          - rclone
          - ripgrep
          - strace
          - tmux
          - tmuxp
          - uv
          - unison
      notify: Reboot
    # This needs to come before AUR packages/paru because of sudo setup.
    - import_tasks: common/tasks.yaml
    # See https://github.com/Jguer/yay/issues/1744
    - name: Check installed AUR packages
      become: false
      ansible.builtin.command: pacman -Qm
      ignore_errors: yes
      register: installed_packages
      changed_when: false
    - name: Install AUR packages
      become: false
      ansible.builtin.command: "paru --noconfirm --noprogressbar --needed --sync {{ item }}"
      when: item not in installed_packages.stdout
      with_items:
        - kopia-bin
        - lazydocker-bin
    - name: Copy package update script
      ansible.builtin.copy:
        src: cachyos/updates.sh
        dest: "/home/{{ username }}/bin/updates.sh"
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Add systemd user units
      ansible.builtin.copy:
        src: "cachyos/{{ item }}"
        dest: "/home/{{ username }}/.config/systemd/user/{{ item }}"
        mode: "644"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop:
        - updates.service
        - updates.timer
    - name: Get UID of user
      getent:
        database: passwd
        key: "{{ username }}"
    - name: Enable and start user timer
      become_user: "{{ username }}"
      ansible.builtin.systemd_service:
        name: updates.timer
        state: started
        scope: user
        enabled: true
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts.getent_passwd[username][1] }}"
  handlers:
    - import_tasks: common/global_handlers.yaml
