- name: Setup hosts after install
  hosts:
    - cachyos_server
  become: true
  vars:
    username: valankar
    dev_username: valankar-dev
  tasks:
    - name: Upgrade packages
      community.general.pacman:
        update_cache: true
        upgrade: true
      notify: Reboot
    - name: Install packages
      community.general.pacman:
        name:
          - compsize
          - distrobox
          - docker
          - docker-buildx
          - docker-compose
          - dua-cli
          - go-task
          - lazygit
          - neovim
          - npm
          - powerline
          - rclone
          - ripgrep
          - sshfs
          - tmux
          - tmuxp
          - uv
          - unison
      notify: Reboot
    - name: Disable password SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        search_string: '#PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
      notify: Reboot
    - name: Enable docker
      ansible.builtin.systemd:
        name: docker.service
        enabled: yes
      notify: Reboot
    - name: Add dev user
      ansible.builtin.user:
        name: "{{ dev_username }}"
        shell: /bin/fish
    - name: Add users to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: [ "{{ username }}", "{{ dev_username }}"]
    - name: Ensure user bin directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/bin"
        state: directory
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Copy package update script
      ansible.builtin.copy:
        src: cachyos/updates.sh
        dest: "/home/{{ username }}/bin/updates.sh"
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Ensure user systemd directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/.config/systemd/user"
        state: directory
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Add systemd kopia unit
      ansible.builtin.copy:
        src: "common/kopia.service"
        dest: "/etc/systemd/system/kopia.service"
        mode: "644"
        owner: "root"
        group: "root"
    - name: Add systemd user units
      ansible.builtin.copy:
        src: "cachyos/{{ item }}"
        dest: "/home/{{ username }}/.config/systemd/user/{{ item }}"
        mode: "644"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop:
        - updates.service
        - updates.timer
    - name: Check if lingering is enabled
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/{{ item }}"
      register: linger_file
      changed_when: false
      loop: [ "{{ username }}", "{{ dev_username }}"]
    - name: Enable linger
      ansible.builtin.command: "loginctl enable-linger {{ item.item }}"
      when: not item.stat.exists
      loop: "{{ linger_file.results }}"
    - name: Get UID of user
      getent:
        database: passwd
        key: "{{ username }}"
    - name: Enable and start user timer
      become_user: "{{ username }}"
      ansible.builtin.systemd_service:
        name: updates.timer
        state: started
        scope: user
        enabled: true
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts.getent_passwd[username][1] }}"
    - name: sudo without password
      ansible.builtin.copy:
        src: common/11-nopasswd
        dest: /etc/sudoers.d/11-nopasswd
        mode: "600"
    # See https://github.com/Jguer/yay/issues/1744
    - name: Check installed AUR packages
      become: false
      ansible.builtin.command: pacman -Qm
      ignore_errors: yes
      register: installed_packages
      changed_when: false
    - name: Install AUR packages
      become: false
      ansible.builtin.command: "paru --noconfirm --noprogressbar --needed --sync {{ item }}"
      when: item not in installed_packages.stdout
      with_items:
        - kopia-bin
        - lazydocker-bin
    - name: Networking sysctl
      ansible.builtin.copy:
        src: common/99-networking.conf
        dest: /etc/sysctl.d/99-networking.conf
        mode: "644"
      notify: Reboot
  handlers:
    - import_tasks: handlers/global_handlers.yaml
