- name: Setup hosts after install
  hosts: cachyos
  become: true
  tasks:
    - name: Upgrade packages
      community.general.pacman:
        update_cache: true
        upgrade: true
      notify: Reboot if needed
    - name: Install packages
      community.general.pacman:
        name:
          - compsize
          - docker
          - docker-buildx
          - docker-compose
          - neovim
          - rclone
          - ripgrep
          - yay
      notify: Reboot if needed
    - name: Enable docker
      ansible.builtin.systemd:
        name: docker.service
        enabled: yes
      notify: Reboot if needed
    - name: Add user valankar to docker group
      ansible.builtin.user:
        name: valankar
        groups: docker
        append: yes
    - name: Ensure bin directory exists
      ansible.builtin.file:
        path: /home/valankar/bin
        state: directory
        mode: "755"
        owner: valankar
        group: valankar
    - name: Copy package update script
      ansible.builtin.copy:
        src: cachyos/updates.sh
        dest: /home/valankar/bin/updates.sh
        mode: "755"
        owner: valankar
        group: valankar
    - name: Ensure user systemd directory exists
      ansible.builtin.file:
        path: "/home/valankar/.config/systemd/user"
        state: directory
        mode: "755"
        owner: valankar
        group: valankar
    - name: Add systemd user units
      ansible.builtin.copy:
        src: "cachyos/{{ item }}"
        dest: "/home/valankar/.config/systemd/user/{{ item }}"
        mode: "644"
        owner: valankar
        group: valankar
      loop:
        - updates.service
        - updates.timer
    - name: Enable linger
      ansible.builtin.command: "loginctl enable-linger valankar"
    - name: Get UID of valankar
      command: id -u valankar
      register: user_id
    - name: Enable and start user timer
      become_user: valankar
      ansible.builtin.systemd_service:
        name: updates.timer
        state: started
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ user_id.stdout }}"
    - name: Networking sysctl
      ansible.builtin.copy:
        src: cachyos/99-networking.conf
        dest: /etc/sysctl.d/99-networking.conf
        mode: "644"
      notify: Reboot if needed
    - name: sudo without password
      ansible.builtin.copy:
        src: cachyos/11-nopasswd
        dest: /etc/sudoers.d/11-nopasswd
        mode: "600"
    # See https://github.com/Jguer/yay/issues/1744
    - name: Check installed yay packages
      become: false
      ansible.builtin.command: pacman -Qm
      ignore_errors: yes
      register: installed_packages
    - name: Install yay packages
      become: false
      ansible.builtin.command: "yay --noconfirm --noprogressbar --needed --sync {{ item }}"
      when: item not in installed_packages.stdout
      with_items:
        - kopia-bin
        - lazydocker-bin
  handlers:
    - name: Reboot if needed
      ansible.builtin.reboot:
      # debug:
      #   msg: Would reboot
