- name: Setup hosts after install
  hosts: cachyos
  become: true
  vars:
    username: valankar
  tasks:
    - name: Upgrade packages
      community.general.pacman:
        update_cache: true
        upgrade: true
      notify: Reboot if needed
    - name: Install packages
      community.general.pacman:
        name:
          - compsize
          - docker
          - docker-buildx
          - docker-compose
          - neovim
          - rclone
          - ripgrep
          - yay
      notify: Reboot if needed
    - name: Enable docker
      ansible.builtin.systemd:
        name: docker.service
        enabled: yes
      notify: Reboot if needed
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
        append: yes
    - name: Ensure bin directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/bin"
        state: directory
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Copy package update script
      ansible.builtin.copy:
        src: cachyos/updates.sh
        dest: "/home/{{ username }}/bin/updates.sh"
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Ensure user systemd directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/.config/systemd/user"
        state: directory
        mode: "755"
        owner: "{{ username }}"
        group: "{{ username }}"
    - name: Add systemd user units
      ansible.builtin.copy:
        src: "cachyos/{{ item }}"
        dest: "/home/{{ username }}/.config/systemd/user/{{ item }}"
        mode: "644"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop:
        - updates.service
        - updates.timer
    - name: Check if lingering is enabled
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/{{ username }}"
      register: linger_file
      changed_when: false
    - name: Enable linger
      ansible.builtin.command: "loginctl enable-linger {{ username }}"
      when: not linger_file.stat.exists
    - name: Get UID of user
      command: "id -u {{ username }}"
      register: user_id
      changed_when: false
    - name: Enable and start user timer
      become_user: "{{ username }}"
      ansible.builtin.systemd_service:
        name: updates.timer
        state: started
        scope: user
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ user_id.stdout }}"
    - name: Networking sysctl
      ansible.builtin.copy:
        src: cachyos/99-networking.conf
        dest: /etc/sysctl.d/99-networking.conf
        mode: "644"
      notify: Reboot if needed
    - name: sudo without password
      ansible.builtin.copy:
        src: cachyos/11-nopasswd
        dest: /etc/sudoers.d/11-nopasswd
        mode: "600"
    # See https://github.com/Jguer/yay/issues/1744
    - name: Check installed yay packages
      become: false
      ansible.builtin.command: pacman -Qm
      ignore_errors: yes
      register: installed_packages
      changed_when: false
    - name: Install yay packages
      become: false
      ansible.builtin.command: "yay --noconfirm --noprogressbar --needed --sync {{ item }}"
      when: item not in installed_packages.stdout
      with_items:
        - kopia-bin
        - lazydocker-bin
  handlers:
    - name: Reboot if needed
      ansible.builtin.reboot:
      # debug:
      #   msg: Would reboot
