- name: Setup hosts after install
  hosts:
    - fedora_server
  become: true
  vars:
    username: valankar
    dev_username: valankar-dev
    tmux_powerline: /usr/share/tmux/powerline.conf
  tasks:
    - name: Upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      notify: Reboot
    - name: Setup copr
      community.general.copr:
        name: "{{ item }}"
      loop:
        - atim/lazydocker
        - dejan/lazygit
    - name: Kopia repo
      ansible.builtin.yum_repository:
        name: Kopia
        description: Kopia
        baseurl: http://packages.kopia.io/rpm/stable/$basearch/
        gpgkey: https://kopia.io/signing-key
        gpgcheck: true
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - bat
          - btop
          - containerd
          - distrobox
          - dnf-automatic
          - docker-cli
          - docker-compose
          - dua-cli
          - duf
          - fd-find
          - fish
          - fzf
          - git
          - go-task
          - kopia
          - lazydocker
          - lazygit
          - neovim
          - python-tmuxp
          - rclone
          - tmux
          - tmux-powerline
          - unison
          - uv
          - vim
      notify: Reboot
    - name: Enable automatic updates
      block:
        - name: Setup config file
          ansible.builtin.copy:
            dest: /etc/dnf/automatic.conf
            mode: "644"
            owner: "root"
            group: "root"
            content: |
              [commands]
              apply_updates = yes
              reboot = when-changed
        - name: Enable systemd service
          ansible.builtin.systemd:
            name: dnf-automatic.timer
            enabled: yes
      notify: Reboot
    - import_tasks: common/tasks.yaml
  handlers:
    - import_tasks: common/global_handlers.yaml
