# https://taskfile.dev

version: '3'

includes:
  common: ../CommonTasks.yml

tasks:
  upgrade:
    deps:
      - task: common:update-packages
    cmds:
      - git push -u origin master
    sources:
      - uv.lock
