- name: sudo without password
  ansible.builtin.copy:
    src: common/11-nopasswd
    dest: /etc/sudoers.d/11-nopasswd
    mode: "600"
- name: Disable password SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    search_string: '#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify: Reboot
- name: Networking sysctl
  ansible.builtin.copy:
    src: common/99-networking.conf
    dest: /etc/sysctl.d/99-networking.conf
    mode: "644"
  notify: Reboot
- name: Enable docker
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
  notify: Reboot
- name: Add users to docker group, generate ssh key, set fish shell
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/fish
    groups: docker
    append: yes
    generate_ssh_key: true
    ssh_key_comment: "{{ item }}@{{ ansible_hostname }}"
  loop: [ "{{ username }}", "{{ dev_username }}"]
- name: Ensure user bin directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/bin"
    state: directory
    mode: "755"
    owner: "{{ username }}"
    group: "{{ username }}"
- name: Ensure user systemd directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/systemd/user"
    state: directory
    mode: "755"
    owner: "{{ username }}"
    group: "{{ username }}"
- name: Add systemd kopia unit
  ansible.builtin.copy:
    src: "common/kopia.service"
    dest: "/etc/systemd/system/kopia.service"
    mode: "644"
    owner: "root"
    group: "root"
- name: Check if lingering is enabled
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ item }}"
  register: linger_file
  changed_when: false
  loop: [ "{{ username }}", "{{ dev_username }}"]
- name: Enable linger
  ansible.builtin.command: "loginctl enable-linger {{ item.item }}"
  when: not item.stat.exists
  loop: "{{ linger_file.results }}"
- name: Setup ssh authorized keys
  block:
    - name: Read username pub key
      ansible.builtin.slurp:
        src: "/home/{{ username }}/.ssh/id_rsa.pub"
      register: username_pub_ssh_key
    - name: Read dev_username pub key
      ansible.builtin.slurp:
        src: "/home/{{ dev_username }}/.ssh/id_rsa.pub"
      register: dev_username_pub_ssh_key
    - name: Allow ssh from dev_username to username
      ansible.posix.authorized_key:
        user: "{{ username }}"
        key: "{{ dev_username_pub_ssh_key.content | b64decode }}"
    - name: Allow ssh from username to dev_username
      ansible.posix.authorized_key:
        user: "{{ dev_username }}"
        key: "{{ username_pub_ssh_key.content | b64decode }}"
- name: Setup tmux config
  block:
  - name: Ensure user tmux config directory exists
    ansible.builtin.file:
      path: "/home/{{ username }}/.config/tmux"
      state: directory
      mode: "755"
      owner: "{{ username }}"
      group: "{{ username }}"
  - name: Setup tmux config
    ansible.builtin.copy:
      dest: "/home/{{ username }}/.config/tmux/tmux.conf"
      mode: "644"
      owner: "{{ username }}"
      group: "{{ username }}"
      content: |
        source {{ tmux_powerline }}
        set -g mouse on
        set-option -g mode-keys vi
