#!/bin/sh
set -e

if [ "$(df -P / | awk 'NR==2 {gsub(/%/, "", $5); print $5}')" -gt 70 ]; then
  echo "Not enough free space"
  exit 1
fi

INSTANCES=$(incus list -c n -f csv)
REMOTE=hbd
for i in $INSTANCES; do
  OUT="incus-exports/$i.$(date +%u).tar"
  incus export $i --compression none --instance-only --optimized-storage - | ssh $REMOTE "cat > $OUT"
  ssh $REMOTE "nohup gzip -f $OUT >/dev/null 2>&1 </dev/null &"
done

fstrim -av
curl -fsS -m 10 --retry 5 -o /dev/null URL
